services:
    app:
        image: laravel
        restart: unless-stopped
        volumes:
            - .:/var/www
            - /var/www/vendor
        depends_on:
            - database
            - redis

    webserver:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - '${HTTP_PORT:-80}:80'
        volumes:
            - ./:/var/www
            - ./.docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
        healthcheck:
            test: ["CMD", "service", "nginx", "status"]
            retries: 3
            timeout: 5s
    database:
        image: mysql:8
        restart: always
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - .docker/data/database:/var/lib/mysql
        ports:
            - '${DB_PORT:-3306}:3306'
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_ROOT_PASSWORD}" ]
            retries: 3
            timeout: 5s
    redis:
        image: redis:alpine
        ports:
            - '${REDIS_PORT:-6379}:6379'
        volumes:
            - .docker/data/redis:/data
        restart: unless-stopped
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            retries: 3
            timeout: 5s
